---
- name: Deploy AirTrail on GKE
  hosts: localhost
  gather_facts: false
  vars_files:
    - inventory/gcp.yml

  roles:
    - role: postgres_k8s
      tags: ["db", "postgres"]
    - role: airtrail_k8s
      tags: ["app", "airtrail"]
